### ISSUE TITLE
Reference implementation

### ISSUE THREAD

**Issue by wiresio** [hiveot/hiveot.github.io#2]
As the WoT reference implementation you are refering to Webthings from Mozilla which features a great software stack, however not completely compliant with the W3C WoT recommendation. If you want to reference an implemenation that follows W3C you might want to add: https://github.com/eclipse/thingweb.node-wot

**Comment by hspaay** [comment]
@wiresio oops, just noticed this issue now. Not sure why I didn't get a notification on it.
Thank you kindly for the correction. I'll update the documentation.
